EREN_CHANGELOG = [
    {
        "version": "2.2",
        "date": "2026-08-07",
        "type": "feature",
        "title": "E.R.E.N Can Now See Images",
        "changes": [
            "You can now attach an image (PNG, JPEG, WEBP, or GIF) to your chat with E.R.E.N - tap the image icon next to the message box",
            "E.R.E.N analyzes the image (with or without a text question) and explains what it sees",
            "The image shows as a thumbnail in the chat and is kept in your conversation history",
        ],
    },
    {
        "version": "2.1",
        "date": "2026-08-07",
        "type": "fix",
        "title": "Mobile Fix: E.R.E.N Fullscreen Sidebar & Keyboard",
        "changes": [
            "Fixed the history sidebar on phones - it no longer gets stuck open, and can now be closed with the X button or by tapping the dimmed background",
            "Fixed typing in the assistant on mobile - what you type is now visible while the phone keyboard is open (dynamic viewport height + keyboard-aware resizing)",
        ],
    },
    {
        "version": "2.0",
        "date": "2026-08-07",
        "type": "feature",
        "title": "YouTube Summaries & Slide Downloads",
        "changes": [
            "E.R.E.N can now summarize YouTube videos - just paste a link and get a beginner-friendly summary (English or Filipino) with headers and bullet points",
            "YouTube summaries download as a .txt file instead of a PowerPoint, so it is easy to save and submit",
            "E.R.E.N now shows slide outlines and answers with a clean layout - headings, bullet points, and numbered lists are rendered nicely",
            "Added a Download PPT button under presentation-style replies so you can export the outline as a real .pptx file",
            "Every code example now comes with its Sample Output, shown in the chat and included in the PPT",
        ],
    },
    {
        "version": "1.1",
        "date": "2026-08-06",
        "type": "fix",
        "title": "E.R.E.N Assistant Wrongly Refusing Questions Fixed",
        "changes": [
            "Fixed a bug that made the AI assistant reply 'looks like a quiz question' to any question it could not answer directly",
            "E.R.E.N now answers freely again (including in Tagalog) and falls back to the built-in rules only when the AI service is unavailable",
        ],
    },
    {
        "version": "1.0",
        "date": "2026-08-04",
        "type": "launch",
        "title": "E.R.E.N AI Assistant Launch",
        "changes": [
            "Integrated the Google Gemini API into the E.R.E.N assistant with a rule-engine fallback",
            "Added full-page /aiassist view with history and new-chat buttons",
            "Added conversation history persisted in localStorage",
            "Added general knowledge, runnable code blocks, and textarea input",
            "Replies in English and Tagalog only",
        ],
    },
]

CHANGELOG = [
    {
        "version": "1.62",
        "date": "2026-08-07",
        "type": "feature",
        "title": "Login with Username or Email",
        "changes": [
            "Login now accepts your username OR your email address - type either one in the single field and it works",
            "Suggested by: Syrez Leodones - mapagmahal 123, di kana mahal",
        ],
    },
    {
        "version": "1.61",
        "date": "2026-08-07",
        "type": "feature",
        "title": "Angular Lesson, Editable Activity & Admin Coins",
        "changes": [
            "New lesson: Angular (Advanced Fundamentals) - watch the official 'Angular: An Origin Story' documentary, with key points, an interactive TypeScript component example, and a quiz",
            "Activities are now answered online: type your Name, Section, and essay answers right on the lesson page, then Download - a neatly formatted DOCX is generated with your answers indented under every question, ready to submit to Google Classroom",
            "Admins can now view and set the coin balance of any user (including their own account) directly from the Users page, with every change recorded in the Activity Log",
            "Fixed answer indentation and formatting (Times New Roman, spacing) in generated activity documents",
        ],
    },
    {
        "version": "1.60",
        "date": "2026-08-06",
        "type": "feature",
        "title": "New Lesson: TypeScript Fundamentals (Advanced Fundamentals)",
        "changes": [
            "Added a brand-new TypeScript lesson to Advanced Fundamentals - every core fundamental (variables, data types, arrays, tuples, unions, functions, interfaces, classes, conditionals, and loops) re-taught in TypeScript",
            "The lesson's code examples are fully interactive - run them right in the browser with Node.js type-stripping",
            "The lesson includes key points and an 8-question quiz, and counts toward your Advanced Fundamentals progress",
            "Updated the landing page, FAQ, and About page to reflect the new 35th lesson",
        ],
    },
    {
        "version": "1.59",
        "date": "2026-08-06",
        "type": "feature",
        "title": "Certificates Need the Long Quiz + Cisco-Style Topic Rating",
        "changes": [
            "Section certificates now also require finishing that section's Long Quiz, not just its lessons - complete the quiz to unlock the certificate",
            "The Full Course certificate now requires every lesson AND every Long Quiz to be finished",
            "After you finish a Long Quiz, a summary screen appears where you rate how tricky each topic was (Very Easy to Very Hard) - just like Cisco's post-assessment survey",
            "Ratings are saved to your account and recorded in the Activity Log, so we can improve the harder lessons",
            "The dashboard shows a lock with a hint on certificate buttons whenever a Long Quiz is still missing",
        ],
    },
    {
        "version": "1.58",
        "date": "2026-08-06",
        "type": "security",
        "title": "Feedback Moderation: Automatic Ban for Spam & Bad Words",
        "changes": [
            "Feedback is now monitored - submitting feedback that contains inappropriate or vulgar words (English or Filipino) automatically bans the account",
            "Sending several feedback messages in a very short window is treated as spam and also triggers an automatic ban",
            "Banned users are logged out immediately, cannot log back in, and are shown the reason on the login page",
            "Admins can ban or unban any member from the Users page with a one-click Ban / Unban button and an optional reason",
            "Banned accounts show a Banned badge next to their name, and every ban/unban action is recorded in the Activity Log",
            "Admins cannot be banned",
            "Admin accounts always keep access - even when their IP is temporarily blocked, admins can still log in",
        ],
    },
    {
        "version": "1.57",
        "date": "2026-08-06",
        "type": "security",
        "title": "Login Security: Failed Attempt Detection & Auto-Lockout",
        "changes": [
            "Every failed login attempt is now recorded with the username tried, IP address, user agent, and exact time - so you can see when someone is trying to break in",
            "Auto-lockout: 5 failed login attempts from the same IP within 30 minutes temporarily blocks that IP from logging in (even with the correct password)",
            "Login messages now tell you how many attempts remain before a block, and show the exact minutes left once blocked",
            "New Admin > Security page shows failed login statistics, every blocked IP with a Blocked badge, the recent attempts list, and one-click Clear buttons per IP or for everything",
            "The admin dashboard shows a warning banner whenever there have been failed login attempts in the last 24 hours",
        ],
    },
    {
        "version": "1.56",
        "date": "2026-08-06",
        "type": "feature",
        "title": "All SQL Injection Lessons Released with a Practice Lab for Every Lesson",
        "changes": [
            "Released all 8 previously 'coming soon' SQL Injection lessons: Types of SQL Injection, UNION-Based, Blind, Real-World Queries, Parameterized Queries, Defense in Depth, Testing & Detection, and Real-World Attack Scenarios",
            "Every SQL Injection lesson now has its own interactive Practice Lab (login bypass, UNION data theft, blind extraction, UPDATE/INSERT/DELETE attacks, second-order injection, safe mode demos, and more)",
            "All 10 SQL Injection lessons now appear unlocked on the dashboard with a Practice Lab button and a green Lab Completed badge once solved",
            "Each lab is a safe browser simulation - no real SQL is executed - with objectives, clickable payloads, a live query console, and a Final Challenge with hints",
            "Each lab still earns 2 leaderboard points and is tracked per lesson in the admin panel",
            "The lesson count grew from 26 to 34, and the SQL Injection section is now fully complete",
        ],
    },
    {
        "version": "1.53",
        "date": "2026-08-06",
        "type": "feature",
        "title": "Like & Heart Reactions on Feedback",
        "changes": [
            "Every feedback now has a heart reaction button on the public feedback page - tap it to like a comment",
            "Admins can see how many likes each feedback received in the admin panel",
            "Admins can still reply to feedback from the admin panel, and the reply shows on the public feedback page",
            "Added a Feedback link to the admin navigation so admins can easily find and reply to feedback",
        ],
    },
    {
        "version": "1.52",
        "date": "2026-08-06",
        "type": "fix",
        "title": "Code Example Tabs Restored & C Channel Credits Added",
        "changes": [
            "Fixed the Code Examples section so lessons show all their language tabs (Python, C++, Java, and C) side by side again",
            "Added the new C tutorial channels to the Video Lesson Credits in the footer",
        ],
    },
    {
        "version": "1.51",
        "date": "2026-08-06",
        "type": "feature",
        "title": "C Now Taught Side by Side in Every Fundamentals Lesson & C Compiler Support",
        "changes": [
            "C is now taught side by side with Python, C++, and Java inside every Fundamentals lesson",
            "Each lesson gained a C tab with a video tutorial, runnable C code, and key points covering the same concept",
            "Topics covered in C: first program, history, variables and data types, input/output, operators, logical operators, conditionals, loops, functions, arrays, and problem solving",
            "C code now runs in the browser through the online Compiler Explorer service (with local GCC when available)",
            "The standalone Code Compiler page now supports C alongside Python, C++, and Java",
        ],
    },
    {
        "version": "1.50",
        "date": "2026-08-06",
        "type": "feature",
        "title": "Coins System, Quiz-First Completion & Coin Unlocks",
        "changes": [
            "Earn 10 coins for every lesson you complete - your coin balance shows in the navbar and dashboard",
            "Mark as Complete now requires taking the lesson quiz first; the button stays locked until your score is saved",
            "Unlock locked lessons with coins: Easy lessons cost 10 coins, Medium cost 20, and Hard cost 30",
            "Each lesson card now shows a difficulty badge (Easy / Medium / Hard) next to its estimated time",
            "Coin unlocks persist per user and are recorded in the admin activity log",
        ],
    },
    {
        "version": "1.49",
        "date": "2026-08-06",
        "type": "fix",
        "title": "Lesson Progress Revert Bug Fixed & Update Popup Always Shows",
        "changes": [
            "Fixed a critical bug where completed lessons would randomly revert to uncompleted",
            "Root cause: a legacy lesson-ID renumbering migration ran on every app startup and shifted lesson progress (id 5+) by +1 whenever no quiz score existed for lesson 10",
            "Removed the destructive one-time migration so lesson progress can no longer be shifted",
            "Reset the shifted lesson and quiz progress for lessons 5+ (lessons 1-4 and all user accounts were kept intact)",
            "Update notification popup now shows once per visit (new tab/session), so it is easy to see without being annoying on every page change",
            "Feedback timestamps now display in Manila time (PHT) on the public feedback page and admin panel",
        ],
    },
    {
        "version": "1.48",
        "date": "2026-08-05",
        "type": "fix",
        "title": "Update Popup Reliability Fix",
        "changes": [
            "Simplified the new update popup to use only sessionStorage for automatic once-per-session display",
            "Popup now shows automatically on every new session without requiring manual browser cache clearing",
            "Removed the localStorage version comparison that was causing the popup to not appear",
        ],
    },
    {
        "version": "1.47",
        "date": "2026-08-05",
        "type": "feature",
        "title": "WordPress Lesson & Expanded Audience",
        "changes": [
            "Added a new Advanced Fundamentals lesson: Building Websites with WordPress (id=34)",
            "Learn WordPress.com vs WordPress.org, themes, plugins, posts and pages, WP-CLI, and security",
            "Updated the landing page hero to welcome all levels - not just first-year students",
            "Course is now positioned for BSIT, Computer Science, and IT students at any level",
            "Advanced Fundamentals section now has 5 lessons; total course has 26 lessons",
        ],
    },
    {
        "version": "1.46",
        "date": "2026-08-05",
        "type": "feature",
        "title": "Update Popup Notifications",
        "changes": [
            "Added a popup that announces new updates whenever a new version is released",
            "The popup shows only once per session - refreshing the page will not show it again",
            "The popup reappears in a new session only when a newer version is available",
            "Added a link to the full Updates page from the popup",
        ],
    },
    {
        "version": "1.45",
        "date": "2026-08-05",
        "type": "feature",
        "title": "Database Fixed Popup & Version Badge",
        "changes": [
            "Added \"Database Fixed!\" popup modal on the landing page announcing the PostgreSQL migration",
            "Added app version badge (v1.45) to the footer",
            "Turned off maintenance mode and restored the live site",
        ],
    },
    {
        "version": "1.44",
        "date": "2026-08-05",
        "type": "fix",
        "title": "Maintenance Popup Fix",
        "changes": [
            "Fixed the maintenance page popup modal not showing by adding the Bootstrap JS bundle",
        ],
    },
    {
        "version": "1.43",
        "date": "2026-08-05",
        "type": "feature",
        "title": "Under Maintenance Mode",
        "changes": [
            "Added an Under Maintenance page with an Important Notice popup modal",
            "Disabled all buttons and links while maintenance is active",
            "Maintenance mode is on by default and can be toggled via the MAINTENANCE_MODE environment variable",
        ],
    },
    {
        "version": "1.42",
        "date": "2026-08-05",
        "type": "fix",
        "title": "PostgreSQL Data Persistence",
        "changes": [
            "Added a PostgreSQL database service to render.yaml so user accounts and progress are no longer lost when the Render service sleeps",
        ],
    },
    {
        "version": "1.41",
        "date": "2026-08-05",
        "type": "notice",
        "title": "Account Information Notice",
        "changes": [
            "Added and later removed an account information loss notice while the database issue was being resolved",
        ],
    },
    {
        "version": "1.40",
        "date": "2026-08-04",
        "type": "fix",
        "title": "Database Auto-Recovery",
        "changes": [
            "Automatically recreate corrupted database tables on startup",
            "Wrap admin account creation in try-except to handle corrupted databases",
            "Wrap table inspection in try-except for fresh databases",
        ],
    },
    {
        "version": "1.39",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Public Feedback Page",
        "changes": [
            "Made the feedback page public and show user avatars",
            "Added a feedback page with category selection",
        ],
    },
    {
        "version": "1.38",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Landing Page Update",
        "changes": [
            "Updated the landing page with new features and an Advanced Fundamentals section",
        ],
    },
    {
        "version": "1.37",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Advanced Fundamentals Lessons",
        "changes": [
            "Added GitHub, Web Deployment, Render, and Netlify lessons",
            "Added admin online/offline tracking",
            "Added admin user progress management",
            "Added auto-migration for the last_seen column on startup",
        ],
    },
    {
        "version": "1.34",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Persistent Avatars",
        "changes": [
            "Store profile avatars in the database as base64 data URIs so they survive Render redeploys",
        ],
    },
    {
        "version": "1.33",
        "date": "2026-08-04",
        "type": "fix",
        "title": "Philippine Timezone",
        "changes": [
            "Show admin timestamps in Philippine local time (UTC+8) instead of UTC",
        ],
    },
    {
        "version": "1.32",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Video Lessons & Estimates",
        "changes": [
            "Added video lesson tabs with per-language YouTube embeds",
            "Added footer credits marquee for video creators",
            "Compute lesson estimates including embedded video durations",
            "Added official Python/C++/Java history documentaries",
        ],
    },
    {
        "version": "1.31",
        "date": "2026-08-04",
        "type": "feature",
        "title": "Admin Dashboard",
        "changes": [
            "Added admin dashboard with activity logs, recent registrations, and user overview",
            "Added a dedicated admin account and route admins to the admin dashboard on login",
        ],
    },
    {
        "version": "1.30",
        "date": "2026-08-03",
        "type": "feature",
        "title": "Programming History Lesson",
        "changes": [
            "Added a Programming History lesson with badge and updated lesson counts",
            "Moved Programming History to lesson 2 position in Fundamentals",
        ],
    },
    {
        "version": "1.29",
        "date": "2026-08-03",
        "type": "feature",
        "title": "Synchronous Compiler",
        "changes": [
            "Made the lesson compiler fully synchronous - no polling",
            "Unified stdin input flow in the compiler UI",
            "Added Java online compiler via Compiler Explorer",
            "Added no-cache headers for HTML to prevent stale compiler JS",
        ],
    },
    {
        "version": "1.28",
        "date": "2026-08-03",
        "type": "fix",
        "title": "Compiler Session Fixes",
        "changes": [
            "Fixed C++ compiler to return results synchronously without a polling session",
            "Use a single gunicorn worker with threads for in-memory run sessions",
        ],
    },
    {
        "version": "1.27",
        "date": "2026-08-03",
        "type": "fix",
        "title": "Render PostgreSQL Fixes",
        "changes": [
            "Require SSL for Render Postgres connections",
            "Added pool pre-ping and connection recycling",
        ],
    },
    {
        "version": "1.26",
        "date": "2026-08-03",
        "type": "feature",
        "title": "Render Deployment",
        "changes": [
            "Deployed to Render with PostgreSQL support, gunicorn, dark mode, and SQL labs",
        ],
    },
    {
        "version": "1.0",
        "date": "2026-08-03",
        "type": "launch",
        "title": "Initial Launch",
        "changes": [
            "CodeFundamentals launched with 19 lessons, long quizzes, certificates, badges, and the SQL Injection Lab",
            "Lessons in Python, C++, Java, and SQL for first-year programming students",
        ],
    },
]
